### ISSUE TITLE
Finish plot screen

### ISSUE THREAD

**Issue by kasimoglou** [kasimoglou/netsim#11]
Add missing fields and fix plot json model.

**Comment by kasimoglou** [comment]
Questions @GeoMSK @vsamtuc for plots screen:
1. `rel` attribute takes as a value the name of plot's parent view?
2. I think we have not talked that much about `select` attribute. Should I leave it a simple textbox for now?
3. Please confirm:
- If `model_type == plot` x and y will be (each) a single value, chosen from dropdowns containing parent view's column names?
- If `model_type == parameter` 
  - if `stat_type == node` then x = 'node' and y = 'data'
  - if `stat_type == network` then there is no x and y='data
  - if `stat_type == node` then x = ['node', 'n_index'] and y='data' ?

**Comment by GeoMSK** [comment]
1. yes, rel is the name of the parent view
2. leave as text box for now, we'll discuss this later
3. correct, except last "if" which is node2node.

copy pasted from my notes:
model_type == plot        --> stat_type == network
- x == dropdown 
- y == dropdown

model_type == parameter   --> stat_type == node|network|node2node 
- stat_type == node: 
  - x == node 
  - y == data 
- stat_type == network: 
  - x == None 
  - y == data 
- stat_type==node2node: 
  - x == [node,n_index] 
  - y == data
