### ISSUE TITLE
Creating nsd by providing project_id and plan_id with the URL

### ISSUE THREAD

**Issue by vsamtuc** [kasimoglou/netsim#2]
The PT wants to be able to create a new NSD providing the project_id and plan_id that the user
is actually seeing at that time. We need to support this at the level of the NSD editor.

**Comment by kasimoglou** [comment]
Test [link with parameters](http://localhost:18880/nsdEdit/html/index.html#!/new_nsd?project_id=PRJ_COSUMMIT_2015&plan_id=PLN1425469116472)
