### ISSUE TITLE
In RESTAPI, Improve the ability to save after a  Conflict

### ISSUE THREAD

**Issue by vsamtuc** [kasimoglou/netsim#20]

**Comment by vsamtuc** [comment]
I implemented in the back-end the following function: when a conflict occurs (error is 409), the response body contains the current object value.

Katerina, you can change the nsd editor to read this attribute (attribute '_rev'), copy it to the new object save again. This should work...

**Comment by kasimoglou** [comment]
Fixed that. When updating an object if status 409 (conflict) is returned I update object's `_rev` attribute and save again silently.
