### ISSUE TITLE
To better organize the creation of plots, we should split the original dataTable into multiple tables

### ISSUE THREAD

**Issue by vsamtuc** [kasimoglou/netsim#32]
The idea is to split incompatible statistics into several tables, and have multiple 'data' tables to begin with.

Furthermore, at a second stage we should implement an SQL 'UNION' operator, as it cannot be simulated by other facilities

**Comment by vsamtuc** [comment]
Giorgo, des to thema kai ta leme thn Trith

**Comment by vsamtuc** [comment]
This is about creating predefined views, together with predefined plots, so that we don't have to remember things like 'Consumed Energy'

**Comment by GeoMSK** [comment]
Have created an nsd with all castalia stats

**Comment by GeoMSK** [comment]
@vsamtuc  @kasimoglou
when/where to load these predefined plots ?
