### ISSUE TITLE
Stderr and logs for each simulation process respectively

### ISSUE THREAD

**Issue by jvlahou** [kasimoglou/netsim#41]
We should start writing error messages in the simulation error files, which concern each different phase of runtime. I want to find out why a simulation is aborted, and i cannot retrieve any information from error files included in the process' simhome.

**Comment by vsamtuc** [comment]
This is now largely done, for the generator. There is still a question about datavis, so I am assigning this to george.

**Comment by GeoMSK** [comment]
Also done for datavis, just need to redirect their output appropriately
