### ISSUE TITLE
x,y currently hardcoded when creating a parameter

### ISSUE THREAD

**Issue by GeoMSK** [kasimoglou/netsim#42]
- stat_type node: 
  - x --> node 
  - y --> data 
- stat_type  network: 
  - x --> None 
  - y --> data 
- stat_type node2node: 
  - x --> [node,n_index]
  - y --> data

This means that the user must create a view with the appropriate column names ("node", "n_index", "data").

**Comment by GeoMSK** [comment]
The backend supports user defined names for x,y other than those listed above.
Checked with:
"Total Consumed Energy" (Network parameter)
"Energy per Node" (Node parameter)

**Comment by GeoMSK** [comment]
Should we force the user to enter node/n_index/data as x,y (regarding parameters) or alter the gui to support custom names for x and y ?

**Comment by kasimoglou** [comment]
Fixed. We have a new attribute `x2` for node2node parameters. @GeoMSK  check it and tell me if it is works as you expected. I won't merge it with `master` until you tell me it's ok (checkout my branch `feature-parameter-xy` in order to test it).

**Comment by GeoMSK** [comment]
Looks ok

**Comment by kasimoglou** [comment]
Ok, thank you. I m closing it.
