### ISSUE TITLE
The vectorl Run and Compule buttons are non-functional

### ISSUE THREAD

**Issue by vsamtuc** [kasimoglou/netsim#53]
There is now a pair of endpoints in the api:

/api/vectorl/obj-id/compile
/api/vectorl/obj-id/run

They return json objects with the results of these operations.
They can be tested on the following simple  'hello_world' program:

import sys;
on sys.Init {
     print("Hello world");
}

**Comment by kasimoglou** [comment]
Discuss: For now vectorl text has to be saved, can we pass the text typed in api calls or secretly save it on compile/run button click?

**Comment by kasimoglou** [comment]
Every output message is included in response twice. Is this a bug?

**Comment by kasimoglou** [comment]
I have implemented an output area and double compilation messages are shown. What I need to now is what types of console output levels do we have (till now I discovered info, error, critical, warning).

Also I do not understand how to handle run's response.

**Comment by vsamtuc** [comment]
(a) The duplicate messages are now fixed. 
(b) These four are the only ones
(c) The 'run'  output contains: 
1.  a standard output and standard error field, 
2. run success or failure (note that a run can fail, e.g. because of array index out of bounds etc).
3. the compilation output (each run does a compile first).

**Comment by vsamtuc** [comment]
An additional issue is that you need to let the user specify a maximum simulation time to run (unless you use the 'Parameters' value) and a "maximum_number of 'steps'"  (a step is an event receipt).  Otherwise, non-terminating programs will produce exorbitant amounts of output.

Look at the admin gui vectorl pages for ideas.
