### ISSUE TITLE
Updating a plot's x-axis does not work

### ISSUE THREAD

**Issue by vsamtuc** [kasimoglou/netsim#65]
If a change is made to the x-axis of an existing plot, the change is not persisted to the repository.
This may also affect other fields (did not test).

**Comment by kasimoglou** [comment]
This happens only to x' y' axis dropdown fields and occurs both to predefined and user-defined plots. Must be some bug with the dropdown. Working on it..

**Comment by kasimoglou** [comment]
Stupid bug caused when we added x and y fields for parameters too. (forgot to make a change when reading a plot)

Closed on 8a14e62d.
